<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Amazon_searchItem_TS</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>0b852bfc-5da3-4854-a340-bfd3d503cc1b</testSuiteGuid>
   <testCaseLink>
      <guid>d7c12cf3-a47a-4dfb-9a92-149a05582495</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC_Amazon_SearchBar_003</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>8309a050-8c38-43d0-9fdf-9a0cc15a07f4</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/SearchData</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>8309a050-8c38-43d0-9fdf-9a0cc15a07f4</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>category</value>
         <variableId>80c270ef-b464-4456-a085-73dd38dc53b2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>8309a050-8c38-43d0-9fdf-9a0cc15a07f4</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>item</value>
         <variableId>7f181f8d-259e-4479-91cd-195b5a9a6783</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
