<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Amazon_Login_TS_2</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>57e525fc-9c31-4885-86ab-7671d0d6d7cd</testSuiteGuid>
   <testCaseLink>
      <guid>a37c14f6-0354-4a4a-8c6b-2c2046cbcb5a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC_Amazon_Login_002</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>b3af4fd1-b6cb-4f4d-8e82-eefbfeb7ae7a</id>
         <iterationEntity>
            <iterationType>RANGE</iterationType>
            <value>1-2</value>
         </iterationEntity>
         <testDataId>Data Files/Login_data</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>b3af4fd1-b6cb-4f4d-8e82-eefbfeb7ae7a</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Email</value>
         <variableId>ad94071d-1d92-4f46-9ea5-e4af824daf19</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>b3af4fd1-b6cb-4f4d-8e82-eefbfeb7ae7a</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Password</value>
         <variableId>cf359f7a-24aa-43ff-ac36-ffda960d5379</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
